services:
  database:
    image: 'mysql/mysql-server:8.0'
    container_name: antony-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
        - "${MYSQL_PORT}:3306"
    volumes:
        - dbdata:/var/lib/mysql

volumes:
    dbdata: