networks:
  antony-network:
    driver: bridge

services:
  app:
    container_name: antony-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - antony-network


  database:
    image: 'mysql/mysql-server:8.0'
    container_name: antony-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - '3306:3306'
    volumes:
        - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - antony-network

  phpmyadmin:
    image: 'phpmyadmin:5.2.1-apache'
    container_name: php-my-admin
    links:
        - database
    environment:
        PMA_HOST: ${PMA_HOST}
        PMA_PORT: ${PMA_PORT}
        PMA_ARBITRARY: 1
    restart: always
    ports:
        - 8081:80
    networks:
      - antony-network

volumes:
    dbdata: